name: Security Vulnerability
description: Report a security vulnerability (⚠️ DO NOT include sensitive details in public issues)
title: "[SECURITY] "
labels: ["security", "high-priority"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT SECURITY NOTICE** ⚠️
        
        Please do NOT include sensitive security details in this public issue.
        
        For serious vulnerabilities, please follow our [Security Policy](../SECURITY.md) and report privately to the maintainers.
        
        This template is for general security-related issues and improvements.

  - type: checkboxes
    id: not-sensitive
    attributes:
      label: Confirmation
      description: Please confirm this is not a sensitive security vulnerability
      options:
        - label: This is NOT a sensitive security vulnerability that could be exploited
          required: true
        - label: I have read the Security Policy and this issue is appropriate for public disclosure
          required: true

  - type: dropdown
    id: security-type
    attributes:
      label: Security Issue Type
      description: What type of security issue is this?
      options:
        - Security enhancement suggestion
        - Security configuration improvement
        - Security documentation issue
        - Dependency security update needed
        - Security tooling improvement
        - Other security-related improvement
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security improvement or non-sensitive issue
      placeholder: A clear description of the security-related improvement or issue
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential security impact if not addressed?
      placeholder: Describe the potential security implications
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: How do you think this should be addressed?
      placeholder: Suggest how to improve the security posture
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant security guidelines, standards, or documentation
      placeholder: Links to security best practices, CVEs, security guides, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true